var data = [
  {
    id: 1,
    nombre: "China",
    edad_aprox: "Casi dos años",
    tamaño: "mediano",
    tipo: "Gato",
    raza: "Cruza",
    genero: "H",
    vacunas: "Todas",
    castrado: false,
    visita_vete: "02-18-2023",
    tratamiento: "ninguno",
    actividades: ["Romper cartón", "Domadora de sillón"],
    cualidades: ["agil"],
    discapacidad: "ninguna",
    pelaje: "Largo",
    caracter: ["amigable"],
    enfermedades: "ninguna",
    comida: ["iams", "pescado"],
    image: "./img/cat-1.jpg",
    adoptado: false,
  },
  {
    id: 2,
    nombre: "Felix",
    edad_aprox: "Dos años",
    tamaño: "mediano",
    tipo: "Gato",
    raza: "Cruza",
    genero: "M",
    vacunas: "Todas",
    castrado: false,
    visita_vete: "02-18-2023",
    tratamiento: "ninguno",
    actividades: ["Romper cartón", "Domadora de sillón"],
    cualidades: ["agil"],
    discapacidad: "ninguna",
    pelaje: "Largo",
    caracter: ["amigable"],
    enfermedades: "ninguna",
    comida: ["iams", "pescado"],
    image: "./img/cat-2.jpg",
    adoptado: false,
  },
  {
    id: 3,
    nombre: "Figaro",
    edad_aprox: "Casi tres años",
    tamaño: "mediano",
    tipo: "Gato",
    raza: "Cruza",
    genero: "M",
    vacunas: "Todas",
    castrado: false,
    visita_vete: "02-18-2023",
    tratamiento: "ninguno",
    actividades: ["Romper cartón", "Domadora de sillón"],
    cualidades: ["agil"],
    discapacidad: "ninguna",
    pelaje: "Largo",
    caracter: ["amigable"],
    enfermedades: "ninguna",
    comida: ["iams", "pescado"],
    image: "./img/cat-3.jpg",
    adoptado: false,
  },
  {
    id: 4,
    nombre: "Gatsby",
    edad_aprox: "Seis años",
    tamaño: "mediano",
    tipo: "Gato",
    raza: "Cruza",
    genero: "M",
    vacunas: "Todas",
    castrado: false,
    visita_vete: "02-18-2023",
    tratamiento: "ninguno",
    actividades: ["Romper cartón", "Domadora de sillón"],
    cualidades: ["agil"],
    discapacidad: "ninguna",
    pelaje: "Largo",
    caracter: ["amigable"],
    enfermedades: "ninguna",
    comida: ["iams", "pescado"],
    image: "./img/cat-4.jpg",
    adoptado: false,
  },
  {
    id: 5,
    nombre: "Luigi",
    edad_aprox: "Dos años",
    tamaño: "mediano",
    tipo: "Gato",
    raza: "Cruza",
    genero: "M",
    vacunas: "Todas",
    castrado: false,
    visita_vete: "02-18-2023",
    tratamiento: "ninguno",
    actividades: ["Romper cartón", "Domadora de sillón"],
    cualidades: ["agil"],
    discapacidad: "ninguna",
    pelaje: "Largo",
    caracter: ["amigable"],
    enfermedades: "ninguna",
    comida: ["iams", "pescado"],
    image: "./img/cat-5.jpg",
    adoptado: false,
  },
  {
    id: 6,
    nombre: "Rocky",
    edad_aprox: "Cuatro años",
    tamaño: "mediano",
    tipo: "Gato",
    raza: "Cruza",
    genero: "M",
    vacunas: "Todas",
    castrado: false,
    visita_vete: "02-18-2023",
    tratamiento: "ninguno",
    actividades: ["Romper cartón", "Domadora de sillón"],
    cualidades: ["agil"],
    discapacidad: "ninguna",
    pelaje: "Largo",
    caracter: ["amigable"],
    enfermedades: "ninguna",
    comida: ["iams", "pescado"],
    image: "./img/cat-6.jpg",
    adoptado: false,
  },
  {
    id: 7,
    nombre: "Romeo",
    edad_aprox: "Casi cinco años",
    tamaño: "mediano",
    tipo: "Gato",
    raza: "Cruza",
    genero: "M",
    vacunas: "Todas",
    castrado: false,
    visita_vete: "02-18-2023",
    tratamiento: "ninguno",
    actividades: ["Romper cartón", "Domadora de sillón"],
    cualidades: ["agil"],
    discapacidad: "ninguna",
    pelaje: "Largo",
    caracter: ["amigable"],
    enfermedades: "ninguna",
    comida: ["iams", "pescado"],
    image: "./img/cat-7.jpg",
    adoptado: false,
  },
  {
    id: 8,
    nombre: "Tiger",
    edad_aprox: "Un año",
    tamaño: "mediano",
    tipo: "Gato",
    raza: "Cruza",
    genero: "M",
    vacunas: "Todas",
    castrado: false,
    visita_vete: "02-18-2023",
    tratamiento: "ninguno",
    actividades: ["Romper cartón", "Domadora de sillón"],
    cualidades: ["agil"],
    discapacidad: "ninguna",
    pelaje: "Largo",
    caracter: ["amigable"],
    enfermedades: "ninguna",
    comida: ["iams", "pescado"],
    image: "./img/cat-8.jpg",
    adoptado: false,
  },
  {
    id: 9,
    nombre: "Tom",
    edad_aprox: "Tres años",
    tamaño: "mediano",
    tipo: "Gato",
    raza: "Cruza",
    genero: "M",
    vacunas: "Todas",
    castrado: false,
    visita_vete: "02-18-2023",
    tratamiento: "ninguno",
    actividades: ["Romper cartón", "Domadora de sillón"],
    cualidades: ["agil"],
    discapacidad: "ninguna",
    pelaje: "Largo",
    caracter: ["amigable"],
    enfermedades: "ninguna",
    comida: ["iams", "pescado"],
    image: "./img/cat-9.jpg",
    adoptado: false,
  },
];
